name: multi_reg_exp
author: Christophe Hurpeau <christophe@hurpeau.com>
version: 0.2.0
homepage: https://github.com/christophehurpeau/dart-multi_reg_exp
description: Find multiple regExp on strings
documentation: https://github.com/christophehurpeau/dart-multi_reg_exp/wiki
environment:
  sdk: '>=1.1.0 <2.0.0'
dependencies:
  unittest: '>=0.9.0 <0.10.0'
