name: multi_reg_exp
version: 0.1.1
author: Christophe Hurpeau <christophe@hurpeau.com>
description: find multiple regExp on strings
homepage: https://github.com/christophehurpeau/dart-multi_reg_exp
documentation: https://github.com/christophehurpeau/dart-multi_reg_exp/wiki
dependencies:
  unittest: '>=0.8.7'
